{"uuid":"46b5fc18-1e94-479c-867a-e69622913451","historyId":"c688d21783d4207b41eea2c7c85e0349","fullName":"com.testingacademy.ex04_Selenium_Mini_Projects.SeleniumProjectEclipse.test_negative_login","labels":[{"name":"package","value":"com.testingacademy.ex04_Selenium_Mini_Projects.SeleniumProjectEclipse"},{"name":"testClass","value":"com.testingacademy.ex04_Selenium_Mini_Projects.SeleniumProjectEclipse"},{"name":"testMethod","value":"test_negative_login"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"LearningSeleniumATB9x"},{"name":"subSuite","value":"com.testingacademy.ex04_Selenium_Mini_Projects.SeleniumProjectEclipse"},{"name":"host","value":"DESKTOP-IJP28Q1"},{"name":"thread","value":"16800@DESKTOP-IJP28Q1.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"test_negative_login","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [Incorrect username or password] but found [* Incorrect username or password]","trace":"java.lang.AssertionError: expected [Incorrect username or password] but found [* Incorrect username or password]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat org.testng.Assert.assertEquals(Assert.java:666)\r\n\tat com.testingacademy.ex04_Selenium_Mini_Projects.SeleniumProjectEclipse.test_negative_login(SeleniumProjectEclipse.java:71)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify that with invalid email, pass, error message is shown on the \"https://rahulshettyacademy.com/locatorspractice/\" ","steps":[],"attachments":[],"parameters":[],"start":1735912116298,"stop":1735912124122}